### ISSUE TITLE
Use border-box to create the borders

### ISSUE THREAD

**Issue by sagikazarmark** [dzello/revealjs-themes#1]
Hi there!

I've been playing with your RevealJS themes (kudos BTW for making them).

I use reveal-md to generate slides from markdown. robot-lung currently requires some HTML change to add the borders, but it seemed inefficient to change reveal-md's HTML template for those four lines, so I tried to come up with a pure CSS solution:

```css
/*********************************************
 * BORDER
 *********************************************/

.reveal {
  box-sizing: border-box;
  border: 30px solid #FF4081;
}

@media (max-width: 840px) {
  .reveal {
    border-width: 15px;
  }
}

.reveal.has-dark-background {
  border: none;
}

.reveal.has-dark-background .controls {
  right: 30px;
  bottom: 30px;
}
```

The only difference I can see is that the progress bar is now within the border and not on the bottom of the page, but
a) I actually think it's better that way.
b) I think it could be positioned to the bottom using absolute positioning

I believe this is a bit more elegant solution as it doesn't require any custom HTML.

WDYT? Let me know if you agree and want me to send a PR.
